version: "3"

services:
  web:
    build: ./backend/cart
    # volumes:
    #   - django-data:/code
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:9000
    ports:
      - "9000:9000"
  frontend:
    restart: always
    container_name: frontend
    build: ./frontend
    ports:
      - "4201:80"
    stdin_open: true
    depends_on:
      - web
# volumes:
# django-data:
#   driver: local
