version: "3.2"
services:
  # redis:
  #   restart: always
  #   image: redis:5
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - db-net
  db:
    restart: always
    image: mysql
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=MYSQL
      # - MYSQL_USER=<<username>>
      # - MYSQL_PASSWORD=<<password>>
      # - MYSQL_ROOT_PASSWORD=<<rootpassword>>
    ports:
      - "3302:3306"
    networks:
      - db-net

  web:
    restart: always
    container_name: web
    command:
      bash -c "python check_db.py --service-name db --ip db --port 3306 &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    # env_file:
    #   - ./backend/settings.ini
    build:
      context: ./backend/cart/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db-net

  frontend:
    restart: always
    command: npm start
    container_name: front
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    stdin_open: true
    depends_on:
      - web
    networks:
      - db-net

networks:
  db-net:
    driver: bridge
