# Generated by Django 4.0.3 on 2022-04-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
